<?xml version="1.0" encoding="utf-8"?><Database Name="Countries" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-0BAGMG4\SQLEXPRESS;Initial Catalog=Countries;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="Countries_module5_DZ.Properties.Settings" SettingsPropertyName="CountriesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table1" Member="Table1">
    <Type Name="Table1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CapitalName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="InhabitantsNumber" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SquareArea" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="WorldPart" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>